site_name: Cancer Prediction
site_url: https://github.com/RHDina/packaging-publishing.git
repo_url: hhttps://github.com/RHDina/packaging-publishing.git
nav:
  - Home: index.md
  - cancer-prediction:
      - cancer model: cancer_prediction/cancer_model.md
  - theme: readthedocs
  - plugins:
      - mkdocstrings
  - watch:
      - .